# Generated by Django 5.0.4 on 2024-04-20 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
